### ISSUE TITLE
small error in the SpecCSP algorithm

### ISSUE THREAD

**Issue by PaulMuadDib** [sccn/BCILAB#14]
The implementation of the equation 4 of the reference article:

 http://doc.ml.tu-berlin.de/bbci/publications/TomDorNolBlaAihMue06.pdf

 ...requires a square root around the denominator of the spectral weights computation:

alpha_opt{c}(k) = max(0, (mu_s{c}(k)-mu_s{3-c}(k)) / (var_s{1}(k) + var_s{2}(k)) );

Best,
Jeff

**Comment by chkothe** [comment]
Hi Jean, this also occurred to me at one point, but according to Section 3.2 in [this](http://doc.ml.tu-berlin.de/bbci/publications/TomDorNolAihMue06.pdf) paper, the lack of a square root in that term is actually intentional (serves as spectral normalization).

**Comment by PaulMuadDib** [comment]
My mistake, I am confusing eq. 3 and 4 and overlooking this important aspect of spectral normalization.
Thank you Christian, I close the issue.
