### ISSUE TITLE
Supergui Error

### ISSUE THREAD

**Issue by djsaunde** [sccn/BCILAB#19]
Hello,

I'm getting the following error when trying to use a few different functions in BCILAB.

Error using supergui (line 122)
supergui error: argument 'fig' must be numeric

Error in inputgui (line 161)
            [tmp tmp2 allobj] = supergui( 'fig', fig, 'minwidth',
            200, 'geomhoriz', g.geometry, 'uilist', g.uilist,
            'geomvert', [g.geomvert(:)' 1 1] );

Error in arg_guidialog (line 194)
[outs,dummy,okpressed] = inputgui('geometry',geometry,
'uilist',uilist,'helpcom',['env_doc ' helptopic],
'title',dialogtitle,'geomvert',geomvert); %#ok<ASGLU>
 
Error while evaluating Menu Callback

In particular, this occurs when I select: Online Analysis > Read Input From > Lab Streaming Layer (among other options). After doing a bit of Googling, it seems that the supergui functionality in MATLAB 2014b and later has been redefined. Is there a workaround here that doesn't involve installing an older version of MATLAB?

**Comment by cboulay** [comment]
This issue is actually in EEGLAB's supergui.m and was fixed several versions ago.

I'm not setup to test BCILAB right now so I don't know if it's even possible, so this question may be silly, but are you using the EEGLAB that comes with BCILAB or is it using a separate EEGLAB?

If you do not have a separate EEGLAB install that is being invoked by BCILAB then you can fix this problem by switching to the devel branch of BCILAB as it comes with a newer version of EEGLAB with this problem fixed.

If you do have a separate EEGLAB install that is being invoked by BCILAB (again, I don't know if this is even possible) then you'll have to update its version.

**Comment by djsaunde** [comment]
Thanks for your quick response! I am using the EEGLAB that comes with BCILAB. 

I switched to the development branch, and everything seems to be working just fine, thanks.

On another note, when trying to stream in data from the lab streaming layer, I get the following console output, after which BCILAB seems to hang:

Looking for a device with type='EEG' ...
Opening an inlet...
The number of channels in the stream does not match the number of labeled channel records. Using numbered labels.
WARNING: The value assigned to srate in set_new is not in the typical range [0.1 100000], but was: 0
WARNING: only 0% of your channel labels match any known cap design; inferred locations might be wrong. Please consider adding your cap to set_infer_chanlocs.  using montage resources:/caps/Standard-10-5-Cap385.cap.
Looking for a marker stream with type='Markers' ...

For reference, I am using the OpenBCI headset. Is there a reason why it is hanging here? Perhaps the marker stream type is incorrect?

**Comment by chkothe** [comment]
By default the LSL plugin is set up to look for not just an EEG stream but
also a marker stream (for event-locked prediction). You can turn that off
by clearing the MarkerQuery argument.

**Comment by djsaunde** [comment]
Great, this worked for me. Thank you!

**Comment by nesmaebrahim** [comment]
please how i switching to the devel branch of BCILAB ? can you help me

**Comment by nesmaebrahim** [comment]
> Thanks for your quick response! I am using the EEGLAB that comes with BCILAB.
> 
> I switched to the development branch, and everything seems to be working just fine, thanks.
> 
> On another note, when trying to stream in data from the lab streaming layer, I get the following console output, after which BCILAB seems to hang:
> 
> Looking for a device with type='EEG' ...
> Opening an inlet...
> The number of channels in the stream does not match the number of labeled channel records. Using numbered labels.
> WARNING: The value assigned to srate in set_new is not in the typical range [0.1 100000], but was: 0
> WARNING: only 0% of your channel labels match any known cap design; inferred locations might be wrong. Please consider adding your cap to set_infer_chanlocs. using montage resources:/caps/Standard-10-5-Cap385.cap.
> Looking for a marker stream with type='Markers' ...
> 
> For reference, I am using the OpenBCI headset. Is there a reason why it is hanging here? Perhaps the marker stream type is incorrect?

How i can switch to Devel branch of BCILAB?
