### ISSUE TITLE
BCILab error after updating EEGLAB version in dependencies folder

### ISSUE THREAD

**Issue by sarwatfatimam** [sccn/BCILAB#31]
I am using Matlab Version R2015b and installed BCILAB (downloaded from Github). Initially, it gave warnings for supergui and eegoptions which was resolved after I added the new version of eeglab in the dependencies folder. After that it gives following error when I try to modify approach. 

**Using deprecated argument "flag_quantile/FlaggedQuantile" in function flt_clean_windows (help: Legacy parameter for pre-2012 methods. Quantile of data windows flagged for removal. Windows are emoved if flagged in all except for some possibly bad channels, controls the aggressiveness of the rejection.).
Cannot query arguments of function flt_ica (likely an issue with the argument definition): Undefined function 'fastif' for input arguments of type 'char'.
Cannot query arguments of function flt_siftpipeline (likely an issue with the argument definition): Undefined function or variable 'hlp_getModelingApproaches'.
Cannot query arguments of function flt_zscore (likely an issue with the argument definition): Function hlp_expWinMovVar does not exist.
Reference to non-existent field 'flt_ica'.

Error in flt_pipeline>order_filters (line 597)
        preferences{end+1} = [remap.(flt.properties.follows{j}),i]; end

Error in hlp_microcache (line 233)
            [varargout{1:nargout}] = f(varargin{:});

Error in flt_pipeline (line 324)
    [ordering,unlinked] =
    hlp_microcache('ordering',@order_filters,struct('name',{allflt.name},'properties',{allflt.properties}),custom_order);

Error in arg_report (line 99)
        exp_eval(func(args{:},'__arg_report__',type));

Error in arg_define>assign_value (line 669)
                    spec.children = arg_report(report_type,spec.sources{pos},[value skip_arg]);

Error in arg_define>expand_spec (line 450)
                spec(s) = assign_value(spec(s),def{1},report_type,caller_name,false,false,false); end

Error in arg_define>process_spec (line 394)
    spec = expand_spec(compressed_spec,'rich',assign_defaults,caller_name);

Error in hlp_microcache (line 233)
            [varargout{1:nargout}] = f(varargin{:});

Error in arg_define>process_spec_cached (line 384)
    [varargout{1:nargout}] = hlp_microcache('spec',@process_spec,spec,report_type,assign_defaults,perform_namecheck);

Error in arg_define (line 176)
        [spec,flat_names,first_names,name2idx,leading_skippable,checks] =
        process_spec_cached(caller_name,compressed_spec,report_type,~nodefaults,nargout==0);

Error in ParadigmDataflowSimplified/calibrate_simple (line 535)
            args = arg_define(varargin, ...

Error in ParadigmBaseSimplified/calibrate (line 183)
            model = self.calibrate_simple('signal',signal,varargin{:});

Error in gui_configapproach>@(varargin)instance.calibrate(varargin{:})

Error in arg_report (line 101)
        func(args{:},'__arg_report__',type);

Error in arg_guidialog (line 105)
rawspec = arg_report('rich', func, params); %#ok<*NODEF>

Error in gui_configapproach (line 37)
result = arg_guidialog(calibrate_func,'params',approach.parameters,'title','BCILAB: Configure approach','Invoke',false);

Error in gui_newapproach>gui_newapproach_OutputFcn (line 65)
        [varargout{1:2}] = gui_configapproach(varargout{1},true);

Error in gui_mainfcn (line 264)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in gui_newapproach (line 28)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating PushTool ClickedCallback

Undefined function or variable 'errordlg2'.

Error in gui_chooseapproach>gui_chooseapproach_OpeningFcn (line 96)
    errordlg2('You first need to create an approach before you can operate on it.');

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in gui_chooseapproach (line 40)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in gui_configapproach (line 19)
    approach = gui_chooseapproach();
 
Error while evaluating PushTool ClickedCallback**

**Comment by sarwatfatimam** [comment]
I have downloaded BCILAB 1.1-beta and added the files from eeglab_13_5_4b in the folder eeglab_10_0_1_0x. It didnot give me any specific warnings. I started BCILAB, loaded the tutorial data, added a new approach, a confgure approach box appears. When I press OK, it gives me error. Can someone please tell me what might be the issue? Thankyou. 

Here is the full output of what I have explained above. 

>> cd F:\BCILAB-1.1;
>> bcilab
starting BCILAB...
running config script F:\BCILAB-1.1\bcilab_config.m...
running startup function...
  The previously loaded EEGLAB path has been replaced.
Loading BCILAB dependencies...
Loading F:\BCILAB-1.1\dependencies\unlocbox-1.1.70...
UnLocBoX version 1.1.70. Copyright 2012-2013 LTS2-EPFL, by Nathanael Perraudin
Loading F:\BCILAB-1.1\dependencies\mlunit-1.5.1\src...
mlUnit has found a built-in assert functions.
Trying to rename mlUnit assert.m...not found.
Loading F:\BCILAB-1.1\dependencies\eeglab_10_0_1_0x...
eeglab: options file is C:\Users\Sarwat Fatima\eeg_options.m
EEGLAB: adding "ADJUST" v1.1.1 (see >> help eegplugin_adjust)
EEGLAB: adding "ARfitStudio" v0.20 (see >> help eegplugin_interpolateSpike)
EEGLAB: adding "BERGEN" v131130 (see >> help eegplugin_wm_correction)
EEGLAB: adding "CIAC" v1.00 (see >> help eegplugin_ciac)
EEGLAB: adding "Cogniscan" to the path; subfolders (if any) might be missing from the path
EEGLAB: adding "EEGlabImport" v1.00 (see >> help eegplugin_BCI2000import)
EEGLAB: adding "EMDLAB" v0.1 (see >> help eegplugin_EMDLAB)
EEGLAB: adding "GEVD" to the path; subfolders (if any) might be missing from the path
EEGLAB: adding "INSTEPascimport" v1.00 (see >> help eegplugin_ascinstep)
EEGLAB: adding "Mutual_Info_Clustering" v1.00 (see >> help eegplugin_miclust)
EEGLAB: adding "NeurOne" v1.0.3.2 (see >> help eegplugin_neurone)
EEGLAB: adding "SASICA-master" v.1.3 (see >> help eegplugin_SASICA)
EEGLAB: adding "WearableSensing" v1.09 (see >> help eegplugin_pop_WearableSensing)
EEGLAB: adding "amica" v1.0 (see >> help eegplugin_amica)
EEGLAB: adding "anteepimport" v1.08 (see >> help eegplugin_eepimport)
EEGLAB: adding "ap_clustering" v1.0 (see >> help eegplugin_ap_clustering)
EEGLAB: adding "bdfplugin" v? (see >> help eegplugin_bdfimport)
EEGLAB: adding "biosig4octmat-" to the path; subfolders (if any) might be missing from the path
EEGLAB: adding "brainmovie" v0.1 (see >> help eegplugin_brainmovie)
EEGLAB: adding "bva-io" v1.58 (see >> help eegplugin_bva_io)
EEGLAB: adding "corrmap" v1.02 (see >> help eegplugin_corrmap)
EEGLAB: adding "ctfimport" v1.03 (see >> help eegplugin_ctfimport)
EEGLAB: adding "cwleegfmri " v0.01 (see >> help eegplugin_cwcorrection)
Fieldtrip functions for dipole localization not found, removing Dipfit2
EEGLAB: adding "dipfit" v2.2 (see >> help eegplugin_dipfit)
EEGLAB: adding "dipfit" v2.3 (see >> help eegplugin_dipfit)
EEGLAB: adding "eeg_toolbox" v1.0 (see >> help eegplugin_eeg_toolbox)
EEGLAB: adding "envtopoForContinuous" v0.10 (see >> help eegplugin_envtopoForContinuous)
EEGLAB: adding "erpssimport" v1.00 (see >> help eegplugin_erpssimport)
EEGLAB: adding "firfilt" v1.6.1 (see >> help eegplugin_firfilt)
EEGLAB: adding "fmrib" v1.21 (see >> help eegplugin_fmrib)
EEGLAB: adding "gtecimport " v3.15.01 (see >> help eegplugin_gtecimport)
EEGLAB: adding "iirfilt" v1.02 (see >> help eegplugin_iirfilt)
EEGLAB: adding "instepascimport" v1.02 (see >> help eegplugin_ascinstep)
EEGLAB: adding "loadcurry " v2.0 (see >> help eegplugin_loadcurry)
EEGLAB: adding "loadhdf" v51.0 (see >> help eegplugin_loadhdf5)
EEGLAB: adding "loadhdf" v51.1 (see >> help eegplugin_loadhdf5)
EEGLAB: adding "loreta" v1.0 (see >> help eegplugin_loreta)
EEGLAB: adding "mutual_info_clustering" v? (see >> help eegplugin_miclust)
EEGLAB: adding "mutual_info_ordering" v? (see >> help eegplugin_miorder)
EEGLAB: adding "neuroimaging4d" v1.00 (see >> help eegplugin_4dneuroimaging)
EEGLAB: adding "std_infocluster" v1.1 (see >> help eegplugin_std_infocluster)
EEGLAB: adding "std_selectICsByCluster" v0.11 (see >> help eegplugin_std_selectICsByCluster)
EEGLAB: adding "xdfimport1.11b" v? (see >> help eegplugin_xdfimport)
Loading F:\BCILAB-1.1\dependencies\cvx-1.21.b795...
 
Testing the cvx distribution. If this script aborts with
an error, please report the error to the authors.
-------------------------------------------------------------
No errors! cvx has been successfully installed.
 
NOTE: The MATLAB path has been updated to point to the cvx distribution.
In order to use cvx regularly, you must save this new path definition.
To accomplish this, add these lines to your startup.m file:
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795\structures
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795\lib
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795\functions
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795\commands
    addpath f:\bcilab-1.1\dependencies\cvx-1.21.b795\builtins
Consult the MATLAB documentation if necessary.
 

code is in F:\BCILAB-1.1\code
data is in F:\BCILAB-1.1\userdata
results are in F:\BCILAB-1.1\userdata
cache is disabled
temp is in F:\BCILAB-1.1-temp

 Welcome to the BCILAB toolbox on DESKTOP-N5E5MEA!

Using deprecated argument "flag_quantile" in function flt_clean_windows (help: Legacy parameter for pre-2012 methods Quantile of data windows flagged for removal. Windows are emoved if flagged in all except for some possibly bad channels, controls the aggressiveness of the rejection.).
Cannot query arguments of function flt_zscore (likely an issue with the argument definition): Function hlp_expWinMovVar does not exist.
Undefined function 'eval' for input arguments of type 'double'.

Error in arg_guidialog (line 218)
               v = eval(v); % convert back to numeric (or object, or cell) value

Error in gui_configapproach (line 38)
result = arg_guidialog(calibrate_func,'params',approach.parameters,'title','BCILAB: Configure approach','Invoke',false);

Error in gui_newapproach>gui_newapproach_OutputFcn (line 65)
        [varargout{1:2}] = gui_configapproach(varargout{1},true);

Error in gui_mainfcn (line 264)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in gui_newapproach (line 28)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating PushTool ClickedCallback

Undefined function 'eval' for input arguments of type 'double'.

Error in arg_guidialog (line 218)
               v = eval(v); % convert back to numeric (or object, or cell) value

Error in gui_configapproach (line 38)
result = arg_guidialog(calibrate_func,'params',approach.parameters,'title','BCILAB: Configure approach','Invoke',false);

Error in gui_newapproach>gui_newapproach_OutputFcn (line 65)
        [varargout{1:2}] = gui_configapproach(varargout{1},true);

Error in gui_mainfcn (line 264)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in gui_newapproach (line 28)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating PushTool ClickedCallback

**Comment by Mukhrad** [comment]
use subs() instead of eval() in the arg_guidialog

**Comment by sarwatfatimam** [comment]
Okay. Thankyou. It is working now. Do you why I might be getting the following warning?

_Using deprecated argument "flag_quantile" in function flt_clean_windows (help: Legacy parameter for pre-2012 methods Quantile of data windows flagged for removal. Windows are emoved if flagged in all except for some possibly bad channels, controls the aggressiveness of the rejection.).
Cannot query arguments of function flt_zscore (likely an issue with the argument definition): Function hlp_expWinMovVar does not exist._

**Comment by sarwatfatimam** [comment]
I am following the hands-on tutorial from this presentation. ftp://sccn.ucsd.edu/pub/bcilab/presentations/2012-06-17b%20Workshop%20Beijing%20Practicum.pdf. After trying out the "Calibrating the new model" command on slide 57: I get the computation failed error: 

beginning new computation...
io_loadset(): loading F:\BCILAB-1.1\userdata\tutorial\flanker_task\12-08-002_ERN.vhdr...
pop_loadbv(): reading header file
pop_loadbv(): reading EEG data
pop_loadbv(): scaling EEG data
pop_loadbv(): reading marker file
readlocs(): 'sfp' format assumed from file extension
Channel lookup: no location for RE,LE,VEOG
Send us standard location for your channels at eeglab@sccn.ucsd.edu
Radius values: 0.0999117 (mean) +/- 4.20252e-05 (std)
Note: automatically convert XYZ coordinates to spherical and polar

Computation failed; error trace:
 Class must be 'single' or 'double'.
 occurred in: 
   rat: 121
   flt_resample: 86
   hlp_wrapresults: 51
   exp_eval: 133
   exp_beginfun: 423
   set_makepos: 42
   hlp_wrapresults: 51
   exp_eval: 133
   exp_beginfun: 423
   flt_spectrum: 63
   hlp_wrapresults: 51
   exp_eval: 133
   @(f,a,frame__f2)feval(f,a{:}): 0
   hlp_scope: 51
   exp_eval_optimized: 48
   ParadigmDataflowSimplified.calibrate_simple: 549
   ParadigmBaseSimplified.calibrate: 182
   @(varargin)instance.calibrate(varargin{:}): 0
   @(trainset,varargin)utl_complete_model(calibrate_func('collection',{trainset},varargin{:}),predict_func): 704
   utl_searchmodel: 167
   hlp_getresult: 47
   par_beginschedule: 157
   run_computation: 756
   @(f,a,frame__f1)feval(f,a{:}): 0
   hlp_scope: 51
   bci_train: 730
   pushbutton1_Callback: 156
   gui_mainfcn: 95
   gui_calibratemodel: 30
   @(hObject,eventdata)gui_calibratemodel('pushbutton1_Callback',hObject,eventdata,guidata(hObject)): 0

beginning new computation...
io_loadset(): loading F:\BCILAB-1.1\userdata\tutorial\flanker_task\12-08-002_ERN.vhdr...
pop_loadbv(): reading header file
pop_loadbv(): reading EEG data
pop_loadbv(): scaling EEG data
pop_loadbv(): reading marker file
readlocs(): 'sfp' format assumed from file extension
Channel lookup: no location for RE,LE,VEOG
Send us standard location for your channels at eeglab@sccn.ucsd.edu
Radius values: 0.0999117 (mean) +/- 4.20252e-05 (std)
Note: automatically convert XYZ coordinates to spherical and polar

Computation failed; error trace:
 Class must be 'single' or 'double'.
 occurred in: 
   rat: 121
   flt_resample: 86
   hlp_wrapresults: 51
   exp_eval: 133
   exp_beginfun: 423
   set_makepos: 42
   hlp_wrapresults: 51
   exp_eval: 133
   exp_beginfun: 423
   flt_spectrum: 63
   hlp_wrapresults: 51
   exp_eval: 133
   @(f,a,frame__f2)feval(f,a{:}): 0
   hlp_scope: 51
   exp_eval_optimized: 48
   ParadigmDataflowSimplified.calibrate_simple: 549
   ParadigmBaseSimplified.calibrate: 182
   @(varargin)instance.calibrate(varargin{:}): 0
   @(trainset,varargin)utl_complete_model(calibrate_func('collection',{trainset},varargin{:}),predict_func): 704
   utl_searchmodel: 167
   hlp_getresult: 47
   par_beginschedule: 157
   run_computation: 756
   @(f,a,frame__f1)feval(f,a{:}): 0
   hlp_scope: 51
   bci_train: 730
   pushbutton1_Callback: 156
   gui_mainfcn: 95
   gui_calibratemodel: 30
   @(hObject,eventdata)gui_calibratemodel('pushbutton1_Callback',hObject,eventdata,guidata(hObject)): 0

**Comment by Mukhrad** [comment]
I'm facing same error, when I found the solution I will forward it.

**Comment by Mukhrad** [comment]
To solve this issue use bcilab-develop

**Comment by sarwatfatimam** [comment]
I am still getting the same error. From where did you download the bcilab-develop version? I used bcilab-master which I downloaded frmom Github.

**Comment by Mukhrad** [comment]
https://github.com/sccn/BCILAB/tree/devel?files=1

**Comment by sarwatfatimam** [comment]
Thank you, It's working now.

**Comment by bayan34343** [comment]
hello
I have the same problem but why this file in https://github.com/sccn/BCILAB/tree/devel?files=1
i cant download it 
Uploads are disabled.
File uploads require push access to this repository.
plz help me

**Comment by bayan34343** [comment]
hi   
I have almost the same problem  when I want do new approach and choose csp or any approach give me this error plz help me...

Welcome to the BCILAB toolbox on Freeee-PC!

Error using errordlg2 (line 2)
dialogs disabled.

Error in gui_chooseapproach>gui_chooseapproach_OpeningFcn (line 96)
    errordlg2('You first need to create an approach before you can operate on it.');

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in gui_chooseapproach (line 40)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in gui_configapproach (line 19)
    approach = gui_chooseapproach();
 
Error while evaluating Menu Callback

Error using inputgui (line 2)
dialogs disabled.

Error in arg_guidialog (line 119)
[outs,dummy,okpressed] = inputgui('geometry',geometry, 'uilist',uilist,'helpcom',['doc '
char(func)], 'title',dialogtitle,'geomvert',geomvert); %#ok<ASGLU>

Error in gui_configapproach (line 38)
result = arg_guidialog(calibrate_func,'params',approach.parameters,'title','BCILAB: Configure
approach');

Error in gui_newapproach>gui_newapproach_OutputFcn (line 65)
        [varargout{1:2}] = gui_configapproach(varargout{1},true);

Error in gui_mainfcn (line 264)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in gui_newapproach (line 28)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating Menu Callback
