### ISSUE TITLE
Virus on BCILAB?

### ISSUE THREAD

**Issue by s86100** [sccn/BCILAB#44]
Hello,

I installed BCILAB on my computer, however, later my virus scanner found a virus "Win.Trojan.Agent-1864973" from BCILAB folder.

![screen shot 2018-01-22 at 4 47 10 pm](https://user-images.githubusercontent.com/22102516/35415539-fb6a7248-01f3-11e8-97ed-2a8129776a11.png)

![screen shot 2018-01-25 at 5 19 07 pm](https://user-images.githubusercontent.com/22102516/35415547-05883ae4-01f4-11e8-92fd-ef84428145e6.png)

**Comment by chkothe** [comment]
This is most likely a false positive, but feel free to exclude that file; chances are that this particular mex file isn't needed by any particular BCILAB workflow.
