### ISSUE TITLE
Status of BCILAB

### ISSUE THREAD

**Issue by nahawtho** [sccn/BCILAB#54]
I tried downloading BCIlab a couple weeks ago for matlab 18b, but there appeared to be errors on the code. What is the status on the current master branch, and are there any editions recommended for osx High Sierra 10.13? I am thinking of using EEGLAB because I have had success w them in the past, but i am hesitant to give up the breadth bcilab offers, and its real-time capabilities.

**Comment by chkothe** [comment]
Recently we've merged some fixes for R2018b on MacOS specifically into the devel branch, and we've made devel the default branch of the repo, i.e., the one that gets checked out initially upon cloning (though the readme's may not yet have been updated to reflect that). However, there may well be plenty of other areas in the codebase that would have to be ported to the latest MATLAB version at some point.

**Comment by shirareznik** [comment]
Hi,
Any update?
I had a pipeline working on 2018a and it fails to run over 2018b (Win 64).
Many thanks

(I've also tried neuropype, but it doesn't seem to be in production level- the most simple functionality is not robust to very slight changes from the examples- even importing a set file crushes over some numpy error, or it simply finishes with no helpful error message, and contrary to matlab- one cannot even debug it easily)
