### ISSUE TITLE
 new approach in BCILAB 1.2 

### ISSUE THREAD

**Issue by abujbr** [sccn/BCILAB#64]
I get this error every time I click on new approach in BCILAB 1.2 I'm using Matlab R2018a

 Welcome to the BCILAB toolbox on DESKTOP-C16UG75!

Warning: 'popupmenu' control requires a scalar Value.
Control will not be rendered until all of its parameter values are valid 
> In matlab.hg.internal.openfigLegacy (line 128)
  In gui_mainfcn>local_openfig (line 286)
  In gui_mainfcn (line 158)
  In gui_calibratemodel (line 30) 
Using deprecated argument "flag_quantile/FlaggedQuantile" in function flt_clean_windows (help: Legacy parameter for pre-2012 methods. Quantile of data windows flagged for removal. Windows are emoved if flagged in all except for some possibly bad channels, controls the aggressiveness of the rejection.).
Cannot query arguments of function flt_siftpipeline (likely an issue with the argument definition): Undefined function or variable 'hlp_getModelingApproaches'.
Cannot query arguments of function flt_zscore (likely an issue with the argument definition): Function hlp_expWinMovVar does not exist.
Error using supergui (line 122)
supergui error: argument 'fig' must be numeric

Error in inputgui (line 161)
            [tmp tmp2 allobj] = supergui( 'fig', fig, 'minwidth', 200, 'geomhoriz', g.geometry, 'uilist', g.uilist,
            'geomvert', [g.geomvert(:)' 1 1] );

Error in arg_guidialog (line 194)
[outs,dummy,okpressed] = inputgui('geometry',geometry, 'uilist',uilist,'helpcom',['env_doc ' helptopic],
'title',dialogtitle,'geomvert',geomvert); %#ok<ASGLU>

Error in gui_configapproach (line 37)
result = arg_guidialog(calibrate_func,'params',approach.parameters,'title','BCILAB: Configure approach','Invoke',false);

Error in gui_newapproach>gui_newapproach_OutputFcn (line 65)
        [varargout{1:2}] = gui_configapproach(varargout{1},true);

Error in gui_mainfcn (line 262)
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in gui_newapproach (line 26)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in gui_calibratemodel>gui_calibratemodel_OpeningFcn (line 50)
    approach = gui_newapproach;

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in gui_calibratemodel (line 30)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating PushTool ClickedCallback.

**Comment by arnodelorme** [comment]
You need to download the latest version of BCILAB where this bug has been fixed.
