### ISSUE TITLE
Ridge learner - classification or regression algorithm?

### ISSUE THREAD

**Issue by Izabel94** [sccn/BCILAB#65]
I am bit confused with ml_trainridge.m documentation. 

According to the explanation: 
% Ridge regression [1] is a generalization of basic multivariate regression which in addition
% includes a regularization parameter.
This should be a linear regression algorithm. When I use it, automatically chosen evaluation metric is mse, which also supports this. 

But, this example from the same file 

% Examples:
%   as before, but using a non-default regularization parameter (here: 0.1)
%   model = ml_trainlogreg(trials,targets,0.1)

seems like it is a logistic regression classification algorithm with ridge regularization. 
So, is it a classifier or regression?

**Comment by chkothe** [comment]
Hi Izabel, I think this was a copy-paste error in the example.

**Comment by Izabel94** [comment]
Thanks for the clarification and prompt response.
