### ISSUE TITLE
invalid MEX-file EEGLAB fieldtrip

### ISSUE THREAD

**Issue by tcassim00** [sccn/BCILAB#73]
<img width="628" alt="Screen Shot 2023-01-25 at 1 08 57 AM" src="https://user-images.githubusercontent.com/123541279/214511133-e304926b-f383-4f8e-892e-57edf8fcda4e.png">

EEGLAB gives me this error when i'm trying to open some EEG data.

**Comment by arnodelorme** [comment]
The message indicates that the problem is with Fieldtrip. You should try to install manually an earlier version of the Fieldtrip plugin. 

https://eeglab.org/others/EEGLAB_Extensions.html#to-uninstall-a-plugin
